# Chart Releaser configuration
owner: sheza-dev
git-repo-url: https://github.com/sheza-dev/genieacs-container
charts-repo-url: https://sheza-dev.github.io/genieacs-container
packages-with-index: false
index-path: index.yaml
release-name-template: "{{ .Name }}-{{ .Version }}"

