#!/bin/sh
# install.sh — GenieACS Container: automated production install
# Usage: sudo sh install.sh
# Supports: Debian / Ubuntu (amd64 or arm64)
# --------------------------------------------------------

set -e

GENIEACS_IMAGE="drumsergio/genieacs:1.2.16.0"
MONGO_IMAGE="mongo:8.0"
INSTALL_DIR="/opt/genieacs-container"
COMPOSE_FILE="${INSTALL_DIR}/docker-compose.yml"
ENV_FILE="${INSTALL_DIR}/.env"

# ── Colour helpers ──────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'

info()    { printf "${CYAN}[INFO]${NC}  %s\n" "$*"; }
success() { printf "${GREEN}[OK]${NC}    %s\n" "$*"; }
warn()    { printf "${YELLOW}[WARN]${NC}  %s\n" "$*"; }
die()     { printf "${RED}[ERROR]${NC} %s\n" "$*" >&2; exit 1; }

# ── Root check ──────────────────────────────────────────
if [ "$(id -u)" -ne 0 ]; then
  die "Please run as root: sudo sh install.sh"
fi

# ── Banner ──────────────────────────────────────────────
printf "\n${BOLD}${CYAN}"
printf "╔══════════════════════════════════════════════╗\n"
printf "║       GenieACS Container — Auto Installer    ║\n"
printf "║       Production-Ready Docker Deployment     ║\n"
printf "╚══════════════════════════════════════════════╝\n"
printf "${NC}\n"

# ── OS detection ────────────────────────────────────────
if [ -f /etc/os-release ]; then
  . /etc/os-release
  OS_ID="${ID:-unknown}"
else
  OS_ID="unknown"
fi

# ── Helper: generate a random secret ────────────────────
gen_secret() {
  # prefer openssl, fall back to /dev/urandom + tr
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
  else
    tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 64
  fi
}

# ── 1. Install Docker ───────────────────────────────────
install_docker() {
  info "Installing Docker Engine (official script)..."
  apt-get update -qq
  apt-get install -y -qq curl ca-certificates
  curl -fsSL https://get.docker.com | sh
  systemctl enable --now docker
  success "Docker installed."
}

if command -v docker >/dev/null 2>&1; then
  DOCKER_VER=$(docker --version)
  success "Docker already installed: ${DOCKER_VER}"
else
  warn "Docker not found."
  case "${OS_ID}" in
    debian|ubuntu|raspbian|linuxmint)
      install_docker ;;
    *)
      die "Auto-install only supports Debian/Ubuntu. Install Docker manually: https://docs.docker.com/engine/install/" ;;
  esac
fi

# ── 2. Check Docker Compose (v2 plugin) ─────────────────
if docker compose version >/dev/null 2>&1; then
  success "Docker Compose v2 available."
elif command -v docker-compose >/dev/null 2>&1; then
  warn "Only legacy 'docker-compose' found. Installing Compose v2 plugin..."
  apt-get install -y -qq docker-compose-plugin
  success "Docker Compose v2 installed."
else
  info "Installing Docker Compose v2 plugin..."
  apt-get install -y -qq docker-compose-plugin
  success "Docker Compose v2 installed."
fi

# ── 3. Collect configuration ─────────────────────────────
printf "\n${BOLD}── Configuration ───────────────────────────────${NC}\n"

# JWT Secret
printf "GenieACS UI JWT secret [leave empty to auto-generate]: "
read -r INPUT_JWT
if [ -z "${INPUT_JWT}" ]; then
  JWT_SECRET=$(gen_secret)
  info "JWT secret auto-generated."
else
  JWT_SECRET="${INPUT_JWT}"
fi

# MongoDB password
printf "MongoDB root password [leave empty to auto-generate]: "
read -r INPUT_MONGO_PASS
if [ -z "${INPUT_MONGO_PASS}" ]; then
  MONGO_ROOT_PASS=$(gen_secret)
  info "MongoDB password auto-generated."
else
  MONGO_ROOT_PASS="${INPUT_MONGO_PASS}"
fi

# MongoDB user/db (fixed)
MONGO_USER="genieacs"
MONGO_PASS=$(gen_secret)   # dedicated app user password
MONGO_DB="genieacs"

# Log directory on host
printf "Host log directory [default: /var/log/genieacs]: "
read -r INPUT_LOGDIR
LOG_DIR="${INPUT_LOGDIR:-/var/log/genieacs}"

# Host IP / domain for summary
printf "Server IP or domain (for summary, e.g. 192.168.1.10): "
read -r SERVER_HOST
SERVER_HOST="${SERVER_HOST:-localhost}"

# ── 4. Create install directory ──────────────────────────
printf "\n${BOLD}── Setting up ${INSTALL_DIR} ───────────────────${NC}\n"
mkdir -p "${INSTALL_DIR}"
mkdir -p "${LOG_DIR}"
chmod 755 "${LOG_DIR}"
success "Directories created."

# ── 5. Write .env file ───────────────────────────────────
cat > "${ENV_FILE}" <<EOF
# GenieACS Container — environment variables
# Generated by install.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# --- GenieACS ---
GENIEACS_UI_JWT_SECRET=${JWT_SECRET}
GENIEACS_MONGODB_CONNECTION_URL=mongodb://${MONGO_USER}:${MONGO_PASS}@mongo/${MONGO_DB}?authSource=${MONGO_DB}

# --- MongoDB ---
MONGO_INITDB_ROOT_USERNAME=root
MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASS}
MONGO_APP_USER=${MONGO_USER}
MONGO_APP_PASS=${MONGO_PASS}
MONGO_APP_DB=${MONGO_DB}
EOF
chmod 600 "${ENV_FILE}"
success ".env written (permissions 600)."

# ── 6. Write MongoDB init script ─────────────────────────
mkdir -p "${INSTALL_DIR}/mongo-init"
cat > "${INSTALL_DIR}/mongo-init/01-create-user.js" <<EOF
// Create a dedicated GenieACS database user
// Runs once on first MongoDB startup
db = db.getSiblingDB('${MONGO_DB}');
db.createUser({
  user: '${MONGO_USER}',
  pwd: '${MONGO_PASS}',
  roles: [{ role: 'readWrite', db: '${MONGO_DB}' }]
});
EOF
success "MongoDB init script written."

# ── 7. Write docker-compose.yml ──────────────────────────
cat > "${COMPOSE_FILE}" <<'COMPOSE_EOF'
# GenieACS Container — Production docker-compose.yml
# Generated by install.sh — edit to customise
# ------------------------------------------------
services:

  genieacs:
    depends_on:
      mongo:
        condition: service_healthy
    image: GENIEACS_IMAGE_PLACEHOLDER
    restart: unless-stopped
    container_name: genieacs
    env_file: .env
    environment:
      GENIEACS_CWMP_ACCESS_LOG_FILE: /var/log/genieacs/genieacs-cwmp-access.log
      GENIEACS_NBI_ACCESS_LOG_FILE:  /var/log/genieacs/genieacs-nbi-access.log
      GENIEACS_FS_ACCESS_LOG_FILE:   /var/log/genieacs/genieacs-fs-access.log
      GENIEACS_UI_ACCESS_LOG_FILE:   /var/log/genieacs/genieacs-ui-access.log
      GENIEACS_DEBUG_FILE:           /var/log/genieacs/genieacs-debug.yaml
      GENIEACS_EXT_DIR:              /opt/genieacs/ext
    ports:
      - "7547:7547"   # CWMP — TR-069 (CPE devices)
      - "7557:7557"   # NBI  — REST API (billing integration)
      - "7567:7567"   # FS   — File Server (firmware)
      - "3000:3000"   # UI   — Web interface
    volumes:
      - ext_volume:/opt/genieacs/ext
      - LOG_DIR_PLACEHOLDER:/var/log/genieacs
    networks:
      - genieacs_network
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  mongo:
    image: MONGO_IMAGE_PLACEHOLDER
    restart: unless-stopped
    container_name: mongo-genieacs
    env_file: .env
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR:  /var/log/mongodb
    volumes:
      - data_db:/data/db
      - data_configdb:/data/configdb
      - ./mongo-init:/docker-entrypoint-initdb.d:ro
    expose:
      - "27017"
    networks:
      - genieacs_network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

volumes:
  data_db:
  data_configdb:
  ext_volume:

networks:
  genieacs_network:
COMPOSE_EOF

# Replace placeholders with actual values
sed -i "s|GENIEACS_IMAGE_PLACEHOLDER|${GENIEACS_IMAGE}|g" "${COMPOSE_FILE}"
sed -i "s|MONGO_IMAGE_PLACEHOLDER|${MONGO_IMAGE}|g"         "${COMPOSE_FILE}"
sed -i "s|LOG_DIR_PLACEHOLDER|${LOG_DIR}|g"                 "${COMPOSE_FILE}"
success "docker-compose.yml written."

# ── 8. Pull images ───────────────────────────────────────
printf "\n${BOLD}── Pulling Docker images ───────────────────────${NC}\n"
docker pull "${GENIEACS_IMAGE}"
docker pull "${MONGO_IMAGE}"
success "Images pulled."

# ── 9. Start the stack ───────────────────────────────────
printf "\n${BOLD}── Starting GenieACS stack ─────────────────────${NC}\n"
cd "${INSTALL_DIR}"
docker compose up -d
success "Stack started."

# ── 10. Wait for GenieACS UI to respond ──────────────────
printf "\n${BOLD}── Waiting for GenieACS UI (up to 90s) ─────────${NC}\n"
TIMEOUT=90
ELAPSED=0
until docker compose exec -T genieacs wget --spider --quiet http://localhost:3000 2>/dev/null; do
  if [ "${ELAPSED}" -ge "${TIMEOUT}" ]; then
    warn "GenieACS UI did not respond within ${TIMEOUT}s."
    warn "Check logs: docker compose -f ${COMPOSE_FILE} logs genieacs"
    break
  fi
  printf "."
  sleep 5
  ELAPSED=$((ELAPSED + 5))
done
printf "\n"
success "GenieACS UI is up."

# ── 11. Print summary ────────────────────────────────────
printf "\n${BOLD}${GREEN}"
printf "╔══════════════════════════════════════════════════════╗\n"
printf "║             GenieACS — Installation Complete         ║\n"
printf "╚══════════════════════════════════════════════════════╝\n"
printf "${NC}\n"

printf "${BOLD}Access URLs:${NC}\n"
printf "  Web UI (CWMP + management):  http://${SERVER_HOST}:3000\n"
printf "  NBI REST API (billing):      http://${SERVER_HOST}:7557\n"
printf "  CWMP endpoint (TR-069 CPE):  http://${SERVER_HOST}:7547\n"
printf "  File Server (firmware):      http://${SERVER_HOST}:7567\n"

printf "\n${BOLD}Files:${NC}\n"
printf "  Install directory:  ${INSTALL_DIR}\n"
printf "  Credentials file:   ${ENV_FILE}  (keep secret!)\n"
printf "  Log directory:      ${LOG_DIR}\n"

printf "\n${BOLD}Billing Integration (NBI API):${NC}\n"
printf "  Endpoint:   http://${SERVER_HOST}:7557\n"
printf "  Auth:       HTTP Basic (admin user created via GenieACS UI wizard)\n"
printf "  Docs:       https://github.com/genieacs/genieacs/wiki/API-Reference\n"

printf "\n${BOLD}Useful commands:${NC}\n"
printf "  View logs:     docker compose -f ${COMPOSE_FILE} logs -f genieacs\n"
printf "  Stop stack:    docker compose -f ${COMPOSE_FILE} down\n"
printf "  Restart:       docker compose -f ${COMPOSE_FILE} restart\n"

printf "\n${YELLOW}${BOLD}IMPORTANT — First-time setup:${NC}\n"
printf "  1. Open http://${SERVER_HOST}:3000 in your browser\n"
printf "  2. Complete the GenieACS setup wizard (creates admin user)\n"
printf "  3. Use the admin credentials for NBI API calls from your billing system\n"
printf "  4. Store credentials from ${ENV_FILE} in a safe place\n"
printf "\n"
